# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170817_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
